packages:
  - apps/*
  - packages/*

allowBuilds:
  esbuild: true
  react-native-enriched-markdown: true
  unrs-resolver: true

overrides:
  react-native-worklets: 0.10.1

patchedDependencies:
  react-native-enriched-markdown@1.1.0: patches/react-native-enriched-markdown@1.1.0.patch
